---
- name: Configure hypervisor host OS
  hosts: hypervisor
  become: true
  gather_facts: true
#  vars_files:
#    - ~/vault-credentials.yml

  tasks:

    # python3-cryptography required by community.crypto.x509_certificate_pipe
    - name: Install more Python RPM packages
      ansible.builtin.dnf:
        name:
          - python3-cryptography
          - python3-pip
          - python3-pip-wheel
          - python3-jmespath
        state: present

    - name: Start the sysadmin console 'cockpit' if a request comes in
      ansible.builtin.systemd_service:
        name: cockpit.socket
        state: started
        enabled: true

    # CLI equivalents of ansible.posix.sysctl and rhel-system-roles.network
    #   sudo sysctl net.ipv4.ip_forward=1
    #   sudo nmcli connection modify bridge-public0 +ipv4.routes "192.168.135.0/24 192.168.1.135"
    #   sudo nmcli con up bridge-public0
    # https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html
    - name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true

    - name: Install RPM package
      ansible.builtin.dnf:
        name: rhel-system-roles
        state: present

