---
# Create a new virtual machine using libvirt.
# Install and configure the OS using a kickstart file.

# !!! create a single VM 
# is not overriding role defaults with host vars. 
# they have to be supplied on the CLI like this.
# ansible-playbook       \
#  --vault-pass-file ~/my-vault-pass  \
#  -v \
#  --inventory inventories/inventory-single-host.yml \
#  --extra-vars='install_iso=/var/lib/libvirt/images/rhel-8.10-x86_64-dvd.iso'  \
#  --extra-vars='os_variant=rhel8.10'  \
#  playbooks/vm-kickstart.yml

# create a few variables like "volume_image_file_exists"
- name: Add image facts to hostvars
  hosts: hypervisor
  become: true
  gather_facts: false
  roles:
    - name: "check for existing images"
      role: nickhardiman.libvirt.libvirt_image_facts
      vars:
        fqdn: gateway.silvan.uk
        
# !!! If there already is an image file, don't trash it. 

- name: Kickstart a new machine
  hosts: hypervisor
  become: true
  gather_facts: false
  # vars_files:
  #   - ~/vault-credentials.yml
  roles:
  tasks:
    - name: "Kickstart VM on hypervisor {{ inventory_hostname }}"
      ansible.builtin.include_role:
        name: nickhardiman.libvirt.libvirt_machine_kickstart
      vars:
        fqdn: gateway.silvan.uk
